@extends('layouts.app')
@section('navbar')
    @include('layouts.navbar')
@endsection
@section('sidebar')
    @include('layouts.sidebar')
@endsection
@section('footer')
    @include('layouts.footer')
@endsection
@section('cards')
    @include('layouts.cards')
@endsection
@section('title')
    Dashboard
@endsection
@section('bage-header')
    Dashboard
@endsection
